name: flutter_ume
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 0.2.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.6
  vm_service: ^7.1.1
  string_scanner: ^1.1.0
  tuple: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: d0929b7d322bbc7e8a79e4369eb922f3a3b77716

flutter:
