name: flutter_ume
description: UME is an in-app debug kits platform for Flutter apps.
version: 0.1.0
author: zhaorui.dev@bytedance.com
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.0
  vm_service: ^4.2.0
  string_scanner: ^1.0.0
  tuple: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  flutter_coverage_badge: ^0.0.1+1

flutter:
