name: flutter_ume_kit_device
description: Device info kit for flutter_ume.
version: 1.0.0-dev.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ">=0.3.0 <0.4.0"
  system_info: ^1.0.1
  device_info: ^2.0.2
  platform: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
