name: flutter_ume_kit_perf
description: Performance kits for flutter_ume.
version: 0.2.0-dev.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^7.1.1
  flutter_ume: '>=0.2.0-dev.0 <0.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: master

flutter:
